[msg MSG_DUMMY]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[msg MSG_SCHOOL_1STDAY]
[s]If I remember correctly, the[n][clr 2]Ginza Line[clr 27] should take me to[n]Aoyama-Itchome, where school is...[n][w][e]

[msg MSG_TRAIN_WAIT]
[s]Let's wait for the next train...[n][w][e]

[msg MND_E14410100_NG_HIROBA_]
[s][vp 8 2 65535 0 0 0]For now, I better [n]hurry and get to Ann...[n][w][e]

[msg MND_E10920100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]I was supposed to transfer[n]to the [clr 2]Ginza Line[clr 27] at Shibuya...[n][w][e]

[msg MND_E12710100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]If I get on this train[n]right now, I'll be late...[n][w][e]
[s][vp 8 2 65535 0 0 0]I better hurry[n]and get to school...[n][w][e]

[msg MSG_E24310100_DENENTOSI_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Hey, where are you going?[n]Weren't you going to try[n]to find more information?[n][w][e]

[msg MSG_E24330100_DENENTOSI_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Where are you going?[n]Weren't you planning[n]to explore Shibuya today?[n][w][e]

[msg MND_E14410100_NG_YAMANOT]
[s][vp 8 2 65535 0 0 0]For now, I better[n]hurry and get to Ann...[n][w][e]

[msg MND_E10920100_CHK_KIOSUK]
[s][vp 8 2 65535 0 0 0]There's a wide variety[n]of goods all lined up...[n][w][e]
[s][vp 8 2 65535 0 0 0]I don't have the time[n]to choose anything I'd[n]want from here right now...[n][w][e]

[msg MND_E12710100_CHK_KIOSUK]
[s][vp 8 2 65535 0 0 0]There's a wide variety[n]of goods all lined up...[n][w][e]
[s][vp 8 2 65535 0 0 0]I don't have the time[n]to choose anything I'd[n]want from here right now...[n][w][e]

[msg MND_COMMON_CHK_KIOSUKU_0]
[s][vp 8 2 65535 0 0 0]I don't have time to[n]go shopping right now...[n][w][e]

[msg MND_E10920100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]There's all these magazines[n]here that are full of[n]part-time job listings.[n][w][e]
[s][vp 8 2 65535 0 0 0]I wonder what kinds of jobs are[n]available for me around here...[n][w][e]

[msg MND_E12710100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]There's all these magazines[n]here that are full of[n]part-time job listings.[n][w][e]
[s][vp 8 2 65535 0 0 0]I wonder what kinds of jobs are[n]available for me around here...[n][w][e]

[msg MND_E14410100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]Right now, I need[n]to hurry and find Ann...[n][w][e]

[msg MND_COMMON_CHK_BAITO_MAG]
[s][vp 8 2 65535 0 0 0]I don't have time to look[n]for part-time jobs right now...[n][w][e]

[msg MND_E10920100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]It looks like there's[n]an underground shopping[n]district just up ahead.[n][w][e]
[s][vp 8 2 65535 0 0 0]For now, I better head[n]toward the [clr 2]Ginza Line[clr 27]...[n][w][e]

[msg MND_E12710100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]It looks like there's[n]an underground shopping[n]district just up ahead.[n][w][e]
[s][vp 8 2 65535 0 0 0]For now, I should hurry[n]and head straight to school...[n][w][e]

[msg MND_E14410100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]For now, I better[n]hurry and get to Ann...[n][w][e]

[msg MND_E10920100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]The way ahead looks like it[n]connects to Central Street.[n][w][e]
[s][vp 8 2 65535 0 0 0]I better hurry to[n]the [clr 2]Ginza Line[clr 27] for now...[n][w][e]

[msg MND_E12710100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]The way ahead looks like it[n]connects to Central Street.[n][w][e]
[s][vp 8 2 65535 0 0 0]For now, I should hurry[n]and head straight to school...[n][w][e]

[msg MND_E14410100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]She can't be far from here.[n]I'll try searching this area...[n][w][e]

[msg MND_E10920100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]It looks like this store[n]serves freshly squeezed juice.[n][w][e]
[s][vp 8 2 65535 0 0 0]I'll give this place a try[n]when I have the time...[n][w][e]

[msg MND_E12710100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]It looks like this store[n]serves freshly squeezed juice.[n][w][e]
[s][vp 8 2 65535 0 0 0]I'll give this place a try[n]when I have the time...[n][w][e]

[msg MND_E14410100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]Right now, I need[n]to hurry and find Ann...[n][w][e]

[msg MND_COMMON_CHK_JUICEBAR_]
[s][vp 8 2 65535 0 0 0]I don't have time to[n]buy juice right now...[n][w][e]

[msg MND_E10920100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]This looks like a manjuu shop.[n][w][e]
[s][vp 8 2 65535 0 0 0]It seems they sell a variety[n]of manjuus and daifukus here...[n][w][e]

[msg MND_E12710100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]This looks like a manjuu shop.[n][w][e]
[s][vp 8 2 65535 0 0 0]It seems they sell a variety[n]of manjuus and daifukus here...[n][w][e]

[msg MND_E14410100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]Right now, I need to[n]hurry and get to Ann...[n][w][e]

[msg MND_COMMON_CHK_OMIYAGE_S]
[s][vp 8 2 65535 0 0 0]I don't have time to[n]go shopping right now...[n][w][e]

[msg MND_E10920100_NG_GATE_HI]
[s][vp 8 2 65535 0 0 0]I was supposed to transfer[n]to the [clr 2]Ginza Line[clr 27] at Shibuya.[n]I better hurry to the platform...[n][w][e]

[msg MND_E12710100_NG_GATE_HI]
[s][vp 8 2 65535 0 0 0]I don't have time to go[n]back. I better transfer to the[n][clr 2]Ginza Line[clr 27] and head to school...[n][w][e]

[msg MND_E14410100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]She can't be far from here.[n]I'll try searching this area...[n][w][e]

[msg MND_E12710100_NG_GATE_IN]
[s][vp 8 2 65535 0 0 0]I don't have time to go[n]back. I better transfer to the[n][clr 2]Ginza Line[clr 27] and head to school...[n][w][e]

[msg MND_E10920100_NG_GATEOUT]
[s][vp 8 2 65535 0 0 0]The sign above me says Inogami Line.[n][w][e]
[s][vp 8 2 65535 0 0 0]I was supposed to transfer to[n]the [clr 2]Ginza Line[clr 27], but it looks[n]like I'm on the wrong side.[n][w][e]

[msg MND_E14410100_NG_TOKYU_0]
[s][vp 8 2 65535 0 0 0]For now, I better[n]hurry and get to Ann...[n][w][e]

[msg MND_E10920100_GOTO_INOKA]
[s][vp 8 2 65535 0 0 0]The ticket gate for the[n]Inogami Line seems to be up ahead.[n][w][e]
[s][vp 8 2 65535 0 0 0]For now, I better head[n]toward the [clr 2]Ginza Line[clr 27]...[n][w][e]

[msg MND_E12710100_GOTO_INOKA]
[s][vp 8 2 65535 0 0 0]The ticket gate for the[n]Inogami Line seems to be up ahead.[n][w][e]
[s][vp 8 2 65535 0 0 0]For now, I better head[n]toward the [clr 2]Ginza Line[clr 27]...[n][w][e]

[msg MND_COMMON_GOTO_INOKASIR]
[s][vp 8 2 65535 0 0 0]I don't have any reason[n]to get on the Inogami Line...[n][w][e]

[msg MND_E10920100_CHK_ADJUST]
[s][vp 8 2 65535 0 0 0]It's a machine for[n]adjusting ticket fares.[n][w][e]
[s][vp 8 2 65535 0 0 0]I don't need to use it[n]right now, though...[n][w][e]

[msg MND_E12710100_CHK_ADJUST]
[s][vp 8 2 65535 0 0 0]It's a machine for[n]adjusting ticket fares.[n][w][e]
[s][vp 8 2 65535 0 0 0]I don't need to use it[n]right now, though...[n][w][e]

[msg MND_COMMON_CHK_ADJUSTMEN]
[s][vp 8 2 65535 0 0 0]It's a machine for[n]adjusting ticket fares.[n][w][e]
[s][vp 8 2 65535 0 0 0]I don't need to use it[n]right now, though...[n][w][e]

[msg MND_E10920100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]It's a certification[n]photo machine.[n][w][e]
[s][vp 8 2 65535 0 0 0]It seems to have different[n]functions like make-up mode[n]or one that slims your face...[n][w][e]

[msg MND_E12710100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]It's a certification[n]photo machine.[n][w][e]
[s][vp 8 2 65535 0 0 0]It seems to have different[n]functions like make-up mode[n]or one that slims your face...[n][w][e]

[msg MND_E14410100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]Right now, I need[n]to hurry and find Ann...[n][w][e]

[msg MND_COMMON_CHK_PHOTO_MAC]
[s][vp 8 2 65535 0 0 0]It's a certification[n]photo machine.[n][w][e]
[s][vp 8 2 65535 0 0 0]It seems to have different[n]functions like make-up mode[n]or one that slims your face...[n][w][e]

[msg MND_E10920100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]There are barely any keys left[n]in the coin lockers. Many of them[n]are being used by other people...[n][w][e]

[msg MND_E12710100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]There are barely any keys left[n]in the coin lockers. Many of them[n]are being used by other people...[n][w][e]

[msg MND_E14410100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]Right now, I need[n]to hurry and find Ann...[n][w][e]

[msg MND_COMMON_CHK_COIN_LOCK]
[s][vp 8 2 65535 0 0 0]There are barely any keys left[n]in the coin lockers. Many of them[n]are being used by other people...[n][w][e]

[msg MND_E10920100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]There's an image[n]of a product shown[n]on the display.[n][w][e]
[s][vp 8 2 65535 0 0 0]It looks like a touch screen[n]where you can touch the displayed[n]products to purchase them...[n][w][e]

[msg MND_E12710100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]There's an image[n]of a product shown[n]on the display.[n][w][e]
[s][vp 8 2 65535 0 0 0]It looks like a touch screen[n]where you can touch the displayed[n]products to purchase them...[n][w][e]

[msg MND_E14410100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]Right now, I need[n]to hurry and find Ann...[n][w][e]

[msg MND_COMMON_CHK_NEXT_JUIC]
[s][vp 8 2 65535 0 0 0]I don't have time to take[n]a break and buy drinks now...[n][w][e]

[msg MND_E10920100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]It looks like this[n]vending machine sells fruit.[n][w][e]
[s][vp 8 2 65535 0 0 0]There's a variety of different[n]fruits, packed in rows of bags...[n][w][e]

[msg MND_E12710100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]It looks like this[n]vending machine sells fruit.[n][w][e]
[s][vp 8 2 65535 0 0 0]There's a variety of different[n]fruits, packed in rows of bags...[n][w][e]

[msg MND_E14410100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]Right now, I need[n]to hurry and find Ann...[n][w][e]

[msg MND_COMMON_CHK_FRUIT_MAC]
[s][vp 8 2 65535 0 0 0]I think I'll buy some[n]fruit another time...[n][w][e]

