[msg LABEL01]
[f 0 11 3 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0]A new episode is available.[n][f 0 0 0][e]
You may now continue the storyline.[n][f 0 0 0][e]
You can also select your difficulty[n]mode with the Z or C Buttons.[n][f 0 0 0][e]

[msg LABEL02]
[f 0 9 1 0 1 255 255 255 255]Knowing that the battle with GUILT would[n]never be over until it was removed from[n]Adam's body, Caduceus organized a series[n]of dangerous surgical procedures.[n][f 0 0 0][e]
[f 0 9 1 0 1 255 255 255 255]Doctors Derek Stiles and Naomi Kimishima[n]were the sole surgeons assigned to this task;[n]only their combined Healing Touch abilities[n]could defeat Adam.[n][f 0 0 0][e]
[f 0 9 1 0 1 255 255 255 255]The operations would prove to be impossible[n]for all but the most skilled surgeons.[n][f 0 0 0][e]
[f 0 9 1 0 1 255 255 255 255]Records of these procedures are confidential...[n][f 0 0 0][e]
[f 0 10 0][e]

[msg LABEL03 [[x 0x98 0x62][x 0x8E 0xD2][x 0x96 0xBC][x 0x82 0x50][n]]]
[f 0 9 1 0 1 255 255 255 255]Derek Stiles and Naomi Kimishima overcame[n]Adam's ordeals and triumphed over GUILT.[n]But, what does the future hold for these two[n]gifted surgeons...?[n][f 0 0 0][e]
[f 0 9 1 0 1 255 255 255 255]Congratulations! You've completed the most[n]difficult surgeries ever devised. However,[n]remember that you're not actually a doctor,[n]so you shouldn't perform surgery in real life.[n][f 0 0 0][e]
[f 0 9 1 0 1 255 255 255 255]...Unless of course, you are a doctor.[n]In which case, we would advise you not to[n]tell your patients how many tries it took you[n]to complete a game about surgery.[n][f 0 0 0][e]
[f 0 10 0][e]

