//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\..\..\AtlusScriptLib\MessageScriptLanguage\Compiler\Parser\MessageScriptParser.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AtlusScriptLibrary.FlowScriptLanguage.Compiler.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MessageScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IMessageScriptParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MessageScriptParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] MessageScriptParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MessageScriptParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] MessageScriptParser.CompilationUnitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MessageScriptParser.dialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDialog([NotNull] MessageScriptParser.DialogContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MessageScriptParser.dialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDialog([NotNull] MessageScriptParser.DialogContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MessageScriptParser.messageDialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageDialog([NotNull] MessageScriptParser.MessageDialogContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MessageScriptParser.messageDialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageDialog([NotNull] MessageScriptParser.MessageDialogContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MessageScriptParser.speakerName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpeakerName([NotNull] MessageScriptParser.SpeakerNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MessageScriptParser.speakerName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpeakerName([NotNull] MessageScriptParser.SpeakerNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MessageScriptParser.selectionDialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionDialog([NotNull] MessageScriptParser.SelectionDialogContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MessageScriptParser.selectionDialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionDialog([NotNull] MessageScriptParser.SelectionDialogContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MessageScriptParser.tokenText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokenText([NotNull] MessageScriptParser.TokenTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MessageScriptParser.tokenText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokenText([NotNull] MessageScriptParser.TokenTextContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="MessageScriptParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToken([NotNull] MessageScriptParser.TokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MessageScriptParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToken([NotNull] MessageScriptParser.TokenContext context);
}
} // namespace AtlusScriptLib.FlowScriptLanguage.Compiler.Parser
