//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\..\..\AtlusScriptLib\MessageScriptLanguage\Compiler\Parser\MessageScriptParser.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AtlusScriptLibrary.FlowScriptLanguage.Compiler.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MessageScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IMessageScriptParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MessageScriptParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] MessageScriptParser.CompilationUnitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MessageScriptParser.dialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDialog([NotNull] MessageScriptParser.DialogContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MessageScriptParser.messageDialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageDialog([NotNull] MessageScriptParser.MessageDialogContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MessageScriptParser.speakerName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpeakerName([NotNull] MessageScriptParser.SpeakerNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MessageScriptParser.selectionDialog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectionDialog([NotNull] MessageScriptParser.SelectionDialogContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MessageScriptParser.tokenText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokenText([NotNull] MessageScriptParser.TokenTextContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="MessageScriptParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToken([NotNull] MessageScriptParser.TokenContext context);
}
} // namespace AtlusScriptLib.FlowScriptLanguage.Compiler.Parser
